### ISSUE TITLE
Set Up Moodle on OCP4

### ISSUE THREAD

**Issue by cohiggins** [warrenchristian1telus/moodle#13]

**Comment by warrenchristian1telus** [comment]
I have built Moodle and MySQL containers in OCP4. Still having some issues with the route/connection (503 gateway Timeout). Will try to resolve that with Kosthubha this evening.

**Comment by warrenchristian1telus** [comment]
Moodle is now live on OCP4: https://moodle-950003-dev.apps.silver.devops.gov.bc.ca/
