### ISSUE TITLE
Secure Deployment - Auth Keys

### ISSUE THREAD

**Issue by warrenchristian1telus** [warrenchristian1telus/moodle#21]
Ensure any authorization keys, etc. are separated from Github code (public), Dockerhub deployments (Dockerfile, build images), and  securely managed in OpenShift.

We may need to establish some sort of secure repository for these, as they cannot be tracked in Github with the rest of the source. These should most likely be stored along with (or close to) environment variables, as these may need to be configured and deployed per environment (dev, test, prod), although most will be application-wide.

June 14 - We need to investigate the HashiCorp Vault option:
 - Need access to bcgov HashiCorp vault / or start with Github Secrets (Jared to investigate)

**July 15 - Will continue to look into Hashicorp Vault, however we are almost certain to proceed with Github Secrets solution instead.**

**Comment by cohiggins** [comment]
Closing; will open new issue for CICD/Github Secrets
