### ISSUE TITLE
Replace default login page with customized content 

### ISSUE THREAD

**Issue by allanhaggett** [warrenchristian1telus/moodle#36]
The existing login page needs to be customized so that "Microsoft" is replaced with something more appropriate like "BC Government Login."  The email/password form should also be hidden behind a link that says something like "Access as an external facilitator" or perhaps "Access as an invited guest" ...

**Comment by warrenchristian1telus** [comment]
@allanhaggett I've made a quick change to at least get us part of the way there without requiring any code changes. I've added the "BC Government Login" and logo:

![image](https://user-images.githubusercontent.com/70002196/118332779-7f27cc80-b4bf-11eb-9e59-e233491f864e.png)

There was a warning about the endpoints when I made the changes. Would you mind validating that it still works as expected?

Still working on the best way to get full control. There have been some local OCP updates that have set my local development back a bit. Hoping I can have it sorted today or tomorrow and get back to actual development.

**Comment by allanhaggett** [comment]
Tested and it seems to work just fine :) thanks for this!

Can we do a display: none on .forgetpass to hide that "forgot password" link?

**Comment by warrenchristian1telus** [comment]
Login page has been updated with "External Partner Login":

![image](https://user-images.githubusercontent.com/70002196/118870831-cd601580-b89b-11eb-8542-b5fa1c5ce2a6.png)

**Comment by allanhaggett** [comment]
Looks awesome :) thanks again
