### ISSUE TITLE
Determine SSO configuration for Moodle

### ISSUE THREAD

**Issue by cohiggins** [warrenchristian1telus/moodle#7]

**Comment by cohiggins** [comment]
User synchronization; Evaluate downstream options

**Comment by cohiggins** [comment]
Downstream options: 
- User sync from Microsoft 365/Azure AD to Moodle
- Automatic and manual user matching from Microsoft 365/Azure AD to Moodle
- Calendar sync
- Course to Microsoft 365 group sync and shared file repositories
- OneNote assignment submission and feedback types
- Office document embedding using Office web apps
- Fully customizable sign-in experience

**Comment by cohiggins** [comment]
Warren to contact David Jewer / CITZ to complete set up for Moodle and provide credentials

**Comment by warrenchristian1telus** [comment]
Moodle SSO has been configured in test.

Initial testing was successful.

@cohiggins Please Note: Application secret (from Azure) expires in 1 year for test implementations. I believe this would be from April 16th when it was originally created.

**Comment by warrenchristian1telus** [comment]
Moodle SSO has been configured to use production authentication in test, so that any authorized user may access the system.

Testing was successful.
